version: '3.8'

services:
  redis:
    image: redis:7
    container_name: ims-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:6
    container_name: ims-mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    container_name: ims-postgres
    environment:
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_pass
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"